log:
  level: INFO

api:
  # Access to dashboard
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ':443'

providers:
  file:
    filename: "/etc/traefik/file.yml"
