version: '3'

volumes:
  prometheus-data: { }

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
