version: '3'
services:
  postgresql:
    container_name: local-postgresql
    image: postgres
    environment:
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=pwd
       - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - $PWD/pgdata:/var/lib/postgresql/data

